### ISSUE TITLE
Any chances for widget updated event?

### ISSUE THREAD

**Issue by Kaszaq** [miroapp/web-plugins#6]
I need to trigger an action when a widget is updated, especially its text.

Otherwise client will not get notified when someone else modifies a widget. I made a workaround using SELECTION_UPDATED - user clicks something else, probably he could update text of the previous widget he had selected so this can be checked. However I forgot that action would need to be triggered when another user does that as well which I cannot currently get notified of [unless I am missing some something].

Any chances you could add that? Otherwise I will need to reread all objects from time to time and I'd rather avoid that.. :(

**Comment by pltnkv** [comment]
Thank you for your request. We understand that it is inconvenient to put together integrations without `widget_updated` event. We plan to add it, but currently, we don't have an ETA for it.

Till then you can selectively reread text widgets from time to time like this: 
`await miro.board.widgets.get ({type: 'text'})`
