### ISSUE TITLE
Can you please add rotation to card widget?

### ISSUE THREAD

**Issue by Kaszaq** [miroapp/web-plugins#7]
Can you please add rotation to card widget? It is missing from the sdk however rotation of cards itself is handled in Miro.

We use to mark "blocked" cards by rotating them. I would like my plugin to be able to react on this by checking rotation of cards.

**Comment by pltnkv** [comment]
Could you explain please, what "blocked" means in your use case?

**Comment by Kaszaq** [comment]
Hey,

We are using miro as a kanban board. Rotating a card means that a given card is waiting for external dependencies. Usually, these are described in the comment made on that card. However to see clearly that card cannot progress for some reason due to some external dependencies we rotate them 90 degrees on our board.

**Comment by pltnkv** [comment]
I am very sorry for long response. Now you can rotate card-widget via SDK.
